//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ld500.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_LD500_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_LD500			107
#define IDI_SMALL				108
#define IDC_LD500			109
#define IDC_MYICON				2
#define IDM_MANAGE_PORTS		106
#define IDD_PORTS				130
#define IDC_PORTS_LIST			1001
#define IDC_PORTS_RESET			1002
#define IDC_PORTS_REFRESH		1003
#define IDM_TOGGLE_TRACKING		1004
#define IDM_SETTINGS			1005
#define IDD_SETTINGS			131
#define IDC_SETTINGS_ANGLE_OFFSET	1006
#define IDM_TOGGLE_SHADOW		1007
#define IDM_TOGGLE_PERSISTENCE		1008
#define IDC_SETTINGS_GRID_SIZE		1009
#define IDC_SETTINGS_MIN_CLUSTER_CELLS	1010
#define IDC_SETTINGS_MAX_MATCH_DIST	1011
#define IDC_SETTINGS_MAX_MISSED_FRAMES	1012
#define IDC_SETTINGS_MIN_CONFIRM_FRAMES	1013
#define IDC_SETTINGS_MAX_STATIC_PERSISTENCE	1014
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
